name: Run tests

on:
  push:
    paths:
      - 'example.c'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit tests
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
      - run: yarn test